apiVersion: firewall.operator.linode.io/v1alpha1
kind: ClusterFirewall
metadata:
  name: clusterfirewall-sample
  labels:
    app.kubernetes.io/name: cluster-firewall-operator
spec:
  firewallId: <MY_FIREWALL_ID>
  # interval: 1m
  apiKeySecret:
    name: linode-api-key
    key: api-key
    # namespace: <SOMEWHERE>
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-api-key
type: Opaque
stringData:
  api-key: "<MY_API_KEY>"