apiVersion: firewall.operator.linode.io/v1alpha1
kind: ExternalFirewall
metadata:
  name: externalfirewall-sample
  labels:
    app.kubernetes.io/name: external-firewall-operator
spec:
  inboundPolicy: DROP
  outboundPolicy: ACCEPT
  firewallId: <MY_FIREWALL_ID>
  interval: 1m
  apiKeySecret:
    name: linode-api-key
    key: api-key
    # namespace: <SOMEWHERE>
  rules:
    inbound:
      - action: ACCEPT
        label: "allow-nfs-to-worker-nodes"
        protocol: TCP
        ports: "2049"
        # nodeSelector: #Optional, if not specified, apply to all nodes.
        #   lke.linode.com/pool-id: "307324"
      - action: DROP
        label: "deny-random-to-worker-nodes"
        protocol: TCP
        ports: "3000"
        # nodeSelector: #Optional, if not specified, apply to all nodes.
        #   lke.linode.com/pool-id: "307324" 
---
apiVersion: v1
kind: Secret
metadata:
  name: linode-api-key
type: Opaque
stringData:
  api-key: "<MY_API_KEY>"